import type { PostType } from "@/lib/mock-data";

export type SourceFetchType = "rss" | "atom" | "api" | "html";
export type SourceAuthority = "official" | "research" | "media" | "community" | "product";
export type SourceStatus = "ready" | "watch";

export type AiSource = {
  id: string;
  name: string;
  authority: SourceAuthority;
  status: SourceStatus;
  homeUrl: string;
  feedUrl?: string;
  fetchType: SourceFetchType;
  language: "en" | "zh" | "multi";
  cadence: "hourly" | "daily" | "weekly";
  recommendedType: PostType;
  tags: string[];
  reliabilityScore: number;
  notes: string;
};

export const authoritativeSources: AiSource[] = [
  {
    id: "openai-news",
    name: "OpenAI News",
    authority: "official",
    status: "ready",
    homeUrl: "https://openai.com/news/",
    feedUrl: "https://openai.com/news/rss.xml",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["OpenAI", "模型", "产品更新", "安全"],
    reliabilityScore: 98,
    notes: "OpenAI 官方新闻源，适合抓产品发布、研究说明、公司动态。",
  },
  {
    id: "openai-developers",
    name: "OpenAI Developers",
    authority: "official",
    status: "ready",
    homeUrl: "https://developers.openai.com/",
    feedUrl: "https://developers.openai.com/rss.xml",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "tool",
    tags: ["OpenAI API", "开发者", "Agents", "工具"],
    reliabilityScore: 96,
    notes: "OpenAI 开发者内容，适合抓 API、SDK、Cookbook 和工程实践。",
  },
  {
    id: "anthropic-news",
    name: "Anthropic Newsroom",
    authority: "official",
    status: "watch",
    homeUrl: "https://www.anthropic.com/news",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Anthropic", "Claude", "安全", "企业"],
    reliabilityScore: 96,
    notes: "Anthropic 官方新闻页，目前按 HTML 监控，后续可接页面解析器。",
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    authority: "research",
    status: "watch",
    homeUrl: "https://www.anthropic.com/research",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["Anthropic", "AI安全", "对齐", "可解释性"],
    reliabilityScore: 97,
    notes: "Anthropic 官方研究页，适合抓安全、对齐、可解释性研究。",
  },
  {
    id: "google-deepmind-blog",
    name: "Google DeepMind Blog",
    authority: "research",
    status: "ready",
    homeUrl: "https://deepmind.google/discover/blog/",
    feedUrl: "https://deepmind.google/discover/blog/rss.xml",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["DeepMind", "Gemini", "研究", "多模态"],
    reliabilityScore: 96,
    notes: "Google DeepMind 官方博客，适合抓模型、科学 AI 和研究进展。",
  },
  {
    id: "microsoft-ai-blog",
    name: "Microsoft AI Blog",
    authority: "official",
    status: "ready",
    homeUrl: "https://blogs.microsoft.com/ai/",
    feedUrl: "https://blogs.microsoft.com/ai/feed/",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Microsoft", "Copilot", "Azure AI", "企业 AI"],
    reliabilityScore: 93,
    notes: "微软官方 AI 博客，适合抓 Copilot、Azure AI 和企业案例。",
  },
  {
    id: "meta-ai-blog",
    name: "AI at Meta Blog",
    authority: "official",
    status: "watch",
    homeUrl: "https://ai.meta.com/blog/",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Meta AI", "Llama", "开源模型", "研究"],
    reliabilityScore: 94,
    notes: "Meta AI 官方博客，适合跟踪 Llama、开源模型和研究发布。",
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    authority: "community",
    status: "ready",
    homeUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "tool",
    tags: ["Hugging Face", "开源模型", "数据集", "推理"],
    reliabilityScore: 90,
    notes: "Hugging Face 官方社区博客，适合抓开源模型、数据集和工程教程。",
  },
  {
    id: "nvidia-ai-blog",
    name: "NVIDIA AI Blog",
    authority: "official",
    status: "ready",
    homeUrl: "https://blogs.nvidia.com/blog/category/deep-learning/",
    feedUrl: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["NVIDIA", "GPU", "AI基础设施", "机器人"],
    reliabilityScore: 92,
    notes: "NVIDIA 官方 AI/深度学习博客，适合抓算力、推理、机器人和行业案例。",
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    authority: "research",
    status: "ready",
    homeUrl: "https://arxiv.org/list/cs.AI/recent",
    feedUrl: "https://rss.arxiv.org/rss/cs.AI",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["论文", "人工智能", "研究"],
    reliabilityScore: 89,
    notes: "arXiv 人工智能分类，适合抓论文候选，需要后续用 AI 做筛选和摘要。",
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL",
    authority: "research",
    status: "ready",
    homeUrl: "https://arxiv.org/list/cs.CL/recent",
    feedUrl: "https://rss.arxiv.org/rss/cs.CL",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["论文", "NLP", "LLM"],
    reliabilityScore: 89,
    notes: "arXiv 计算语言学分类，适合跟踪 LLM、NLP、Agent 研究。",
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    authority: "research",
    status: "ready",
    homeUrl: "https://arxiv.org/list/cs.LG/recent",
    feedUrl: "https://rss.arxiv.org/rss/cs.LG",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["论文", "机器学习", "模型训练"],
    reliabilityScore: 88,
    notes: "arXiv 机器学习分类，信息量大，建议定时抓取后做去重和打分。",
  },
  {
    id: "bair-blog",
    name: "Berkeley BAIR Blog",
    authority: "research",
    status: "ready",
    homeUrl: "https://bair.berkeley.edu/blog/",
    feedUrl: "https://bair.berkeley.edu/blog/feed.xml",
    fetchType: "rss",
    language: "en",
    cadence: "weekly",
    recommendedType: "opinion",
    tags: ["学术", "机器人", "强化学习", "研究解读"],
    reliabilityScore: 91,
    notes: "伯克利 BAIR 博客，适合抓研究解读和前沿实验。",
  },
  {
    id: "stanford-hai",
    name: "Stanford HAI",
    authority: "research",
    status: "watch",
    homeUrl: "https://hai.stanford.edu/news",
    fetchType: "html",
    language: "en",
    cadence: "weekly",
    recommendedType: "opinion",
    tags: ["Stanford HAI", "AI治理", "政策", "研究"],
    reliabilityScore: 91,
    notes: "斯坦福 HAI 新闻和研究，适合抓 AI 治理、产业报告和研究洞察。",
  },
  {
    id: "deeplearning-ai-batch",
    name: "The Batch by DeepLearning.AI",
    authority: "media",
    status: "ready",
    homeUrl: "https://www.deeplearning.ai/the-batch/",
    feedUrl: "https://www.deeplearning.ai/the-batch/feed/",
    fetchType: "rss",
    language: "en",
    cadence: "weekly",
    recommendedType: "opinion",
    tags: ["The Batch", "Andrew Ng", "AI趋势", "解读"],
    reliabilityScore: 88,
    notes: "DeepLearning.AI 周报，适合抓趋势解读和研究脉络。",
  },
  {
    id: "mit-tech-review-ai",
    name: "MIT Technology Review AI",
    authority: "media",
    status: "watch",
    homeUrl: "https://www.technologyreview.com/topic/artificial-intelligence/",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["MIT Tech Review", "AI新闻", "产业影响"],
    reliabilityScore: 87,
    notes: "技术评论媒体源，适合补充产业影响和社会议题。",
  },
  {
    id: "producthunt-ai",
    name: "Product Hunt AI",
    authority: "product",
    status: "watch",
    homeUrl: "https://www.producthunt.com/topics/artificial-intelligence",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "product",
    tags: ["Product Hunt", "AI产品", "工具发现"],
    reliabilityScore: 82,
    notes: "产品发现源，适合抓热门新工具，但需要结合投票和评论做质量过滤。",
  },
];

export const fetchableSources = authoritativeSources.filter(
  (source) => source.status === "ready" && Boolean(source.feedUrl),
);

export function getSourcesByAuthority(authority: SourceAuthority) {
  return authoritativeSources.filter((source) => source.authority === authority);
}
