import type { PostType } from "@/lib/mock-data";

export type SourceFetchType = "rss" | "atom" | "api" | "html";
export type SourceAuthority = "official" | "research" | "media" | "community" | "product";
export type SourceStatus = "ready" | "watch";

export type AiSource = {
  id: string;
  name: string;
  authority: SourceAuthority;
  status: SourceStatus;
  homeUrl: string;
  feedUrl?: string;
  fetchType: SourceFetchType;
  language: "en" | "zh" | "multi";
  cadence: "hourly" | "daily" | "weekly";
  recommendedType: PostType;
  tags: string[];
  reliabilityScore: number;
  autoIngest: boolean;
  maxItemAgeDays?: number;
  includeKeywords?: string[];
  excludeKeywords?: string[];
  notes: string;
};

export const authoritativeSources: AiSource[] = [
  {
    id: "openai-news",
    name: "OpenAI News",
    authority: "official",
    status: "ready",
    homeUrl: "https://openai.com/news/",
    feedUrl: "https://openai.com/news/rss.xml",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["OpenAI", "模型", "产品更新", "安全"],
    reliabilityScore: 98,
    autoIngest: true,
    maxItemAgeDays: 14,
    notes: "OpenAI 官方一手源，优先覆盖模型发布、产品更新、安全说明与研究动向。",
  },
  {
    id: "anthropic-news",
    name: "Anthropic Newsroom",
    authority: "official",
    status: "watch",
    homeUrl: "https://www.anthropic.com/news",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Anthropic", "Claude", "安全", "企业"],
    reliabilityScore: 96,
    autoIngest: false,
    notes: "Anthropic 官方新闻源，当前先纳入监控位，待补专用 HTML 解析器后再进入定时抓取。",
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    authority: "research",
    status: "watch",
    homeUrl: "https://www.anthropic.com/research",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["Anthropic", "AI安全", "对齐", "可解释性"],
    reliabilityScore: 97,
    autoIngest: false,
    notes: "Anthropic 官方研究页，重点价值高，但当前先监控，后续接 HTML 解析。",
  },
  {
    id: "google-deepmind-blog",
    name: "Google DeepMind / Google AI",
    authority: "research",
    status: "ready",
    homeUrl: "https://blog.google/innovation-and-ai/technology/",
    feedUrl: "https://blog.google/innovation-and-ai/technology/rss/",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["DeepMind", "Gemini", "研究", "多模态"],
    reliabilityScore: 96,
    autoIngest: true,
    maxItemAgeDays: 14,
    includeKeywords: [
      "deepmind",
      "gemini",
      "agent",
      "model",
      "reasoning",
      "robot",
      "robotics",
      "veo",
      "imagen",
      "alphafold",
      "ai",
    ],
    notes: "Google / DeepMind 官方 AI 技术流，抓模型、Agent、多模态、科研突破等高价值更新。",
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Blog",
    authority: "official",
    status: "watch",
    homeUrl: "https://ai.meta.com/blog/",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Meta AI", "Llama", "开源模型", "多模态"],
    reliabilityScore: 94,
    autoIngest: false,
    notes: "Meta AI 官方博客，后续适合补 Llama、多模态和视觉生成相关解析。",
  },
  {
    id: "microsoft-research-blog",
    name: "Microsoft Research Blog",
    authority: "research",
    status: "ready",
    homeUrl: "https://www.microsoft.com/en-us/research/blog/",
    feedUrl: "https://www.microsoft.com/en-us/research/blog/feed/",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["Microsoft", "Copilot", "Agent", "企业 AI"],
    reliabilityScore: 95,
    autoIngest: true,
    maxItemAgeDays: 21,
    includeKeywords: [
      "ai",
      "agent",
      "llm",
      "language model",
      "copilot",
      "reasoning",
      "multimodal",
      "robot",
      "science",
      "foundation model",
    ],
    notes: "微软研究博客用关键词降噪，只保留 AI、Agent、模型、Copilot 等相关研究文章。",
  },
  {
    id: "nvidia-ai-blog",
    name: "NVIDIA AI / Generative AI Blog",
    authority: "official",
    status: "ready",
    homeUrl: "https://blogs.nvidia.com/blog/category/generative-ai/",
    feedUrl: "https://blogs.nvidia.com/blog/category/generative-ai/feed/",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "news",
    tags: ["NVIDIA", "推理部署", "算力", "生成式 AI"],
    reliabilityScore: 92,
    autoIngest: true,
    maxItemAgeDays: 14,
    notes: "NVIDIA 官方生成式 AI / 工程博客，适合补 AI 基础设施、推理和部署实践。",
  },
  {
    id: "huggingface-papers",
    name: "Hugging Face Papers",
    authority: "community",
    status: "watch",
    homeUrl: "https://huggingface.co/papers",
    fetchType: "html",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["Hugging Face", "Papers", "开源模型", "趋势论文"],
    reliabilityScore: 90,
    autoIngest: false,
    notes: "Hugging Face Papers 价值高，但当前无官方 RSS，先纳入监控位。",
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    authority: "research",
    status: "ready",
    homeUrl: "https://arxiv.org/list/cs.AI/recent",
    feedUrl: "https://rss.arxiv.org/rss/cs.AI",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["论文", "人工智能", "研究"],
    reliabilityScore: 89,
    autoIngest: true,
    maxItemAgeDays: 7,
    includeKeywords: [
      "llm",
      "agent",
      "reasoning",
      "multimodal",
      "video",
      "diffusion",
      "retrieval",
      "rag",
      "robot",
      "benchmark",
      "code",
    ],
    notes: "arXiv 作为论文一手流，仅抓最近 7 天且与 LLM、Agent、多模态、RAG 等相关的论文。",
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL",
    authority: "research",
    status: "ready",
    homeUrl: "https://arxiv.org/list/cs.CL/recent",
    feedUrl: "https://rss.arxiv.org/rss/cs.CL",
    fetchType: "rss",
    language: "en",
    cadence: "daily",
    recommendedType: "opinion",
    tags: ["论文", "NLP", "LLM"],
    reliabilityScore: 89,
    autoIngest: true,
    maxItemAgeDays: 7,
    includeKeywords: [
      "llm",
      "agent",
      "reasoning",
      "multimodal",
      "video",
      "diffusion",
      "retrieval",
      "rag",
      "benchmark",
      "alignment",
      "safety",
      "code",
    ],
    notes: "arXiv cs.CL 只保留和 LLM、Agent、多模态、RAG、安全等相关的近期论文。",
  },
  {
    id: "machine-heart",
    name: "机器之心",
    authority: "media",
    status: "watch",
    homeUrl: "https://www.jiqizhixin.com/",
    fetchType: "html",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["机器之心", "中文解读", "论文解读", "产业动态"],
    reliabilityScore: 88,
    autoIngest: false,
    notes: "中文 AI 解读源，当前先保留监控位，后续补站点级解析器。",
  },
  {
    id: "qbitai",
    name: "量子位",
    authority: "media",
    status: "ready",
    homeUrl: "https://www.qbitai.com/",
    feedUrl: "https://www.qbitai.com/feed",
    fetchType: "rss",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["量子位", "中文 AI 热点", "模型更新", "工具"],
    reliabilityScore: 87,
    autoIngest: true,
    maxItemAgeDays: 7,
    includeKeywords: [
      "ai",
      "大模型",
      "agent",
      "openai",
      "anthropic",
      "claude",
      "gpt",
      "gemini",
      "模型",
      "机器人",
      "具身",
      "aigc",
      "多模态",
      "推理",
      "开源",
      "编程",
    ],
    excludeKeywords: ["智能车参考", "robotaxi", "车圈"],
    notes: "量子位作为中文热点补充源，用时间窗和关键词降噪避免泛科技内容混入。",
  },
  {
    id: "ai-tech-review",
    name: "AI 科技评论",
    authority: "media",
    status: "watch",
    homeUrl: "https://www.leiphone.com/category/ai",
    fetchType: "html",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["AI科技评论", "中文解读", "学术趋势", "产业"],
    reliabilityScore: 88,
    autoIngest: false,
    notes: "雷峰网 AI 频道当前先纳入监控位，后续补分类页解析。",
  },
  {
    id: "kr36-ai",
    name: "36氪 AI / 科技流",
    authority: "media",
    status: "ready",
    homeUrl: "https://36kr.com/",
    feedUrl: "https://36kr.com/feed",
    fetchType: "rss",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["36氪", "AI 商业", "创业", "产品"],
    reliabilityScore: 87,
    autoIngest: true,
    maxItemAgeDays: 5,
    includeKeywords: [
      "ai",
      "人工智能",
      "大模型",
      "openai",
      "anthropic",
      "claude",
      "gpt",
      "gemini",
      "agent",
      "机器人",
      "具身",
      "aigc",
      "生成式",
      "多模态",
      "算力",
      "推理",
    ],
    notes: "36氪官方 RSS 会比较杂，因此只保留最近 5 天内的 AI/大模型/机器人/算力相关文章。",
  },
  {
    id: "geekpark-ai",
    name: "极客公园 AI",
    authority: "media",
    status: "watch",
    homeUrl: "https://www.geekpark.net/",
    fetchType: "html",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["极客公园", "产品趋势", "创业故事", "AI"],
    reliabilityScore: 84,
    autoIngest: false,
    notes: "极客公园保留监控位，后续适合补产品与创业趋势解析。",
  },
  {
    id: "xinzhiyuan",
    name: "新智元",
    authority: "media",
    status: "watch",
    homeUrl: "https://aiera.com.cn/",
    fetchType: "html",
    language: "zh",
    cadence: "daily",
    recommendedType: "news",
    tags: ["新智元", "中文 AI 热点", "论文解读", "产业动态"],
    reliabilityScore: 86,
    autoIngest: false,
    notes: "新智元当前先作为中文热点监控位，后续再接专门解析器。",
  },
];

export const fetchableSources = authoritativeSources.filter(
  (source) => source.status === "ready" && Boolean(source.feedUrl),
);

export const autoIngestSources = fetchableSources.filter((source) => source.autoIngest);
export const autoIngestSourceIds = new Set(autoIngestSources.map((source) => source.id));

export function getSourcesByAuthority(authority: SourceAuthority) {
  return authoritativeSources.filter((source) => source.authority === authority);
}

export function extractGeneratedSourceId(postId: string) {
  if (!postId.startsWith("source-")) return null;

  const source = authoritativeSources.find((item) => postId.startsWith(`source-${item.id}-`));
  return source?.id ?? null;
}
